warm: // namespace android add missing syntax namespace aidl {
device/xiaomi/warm/power/power-mode.cpp:75:24: error: expected '}'
   75 | }  // namespace android
      |                        ^
device/xiaomi/warm/power/power-mode.cpp:35:16: note: to match this '{'
   35 | namespace aidl {
      |                ^
1 error generated.

FIXES THIS:

Co-authored-by: kmiit <kmiit@foxmail.com>